// import { Inter } from "next/font/google";
import "../resources/styles.scss";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Study With Me | Relax and Focus with Study Music",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="black">{children}</body>
    </html>
  );
}
